name: CI
on:
  push:
    branches: ['@qbtf/*']
  pull_request:
    branches: ['@qbtf/*']

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm tsc
      - run: pnpm build
      - run: pnpm test
      - run: pnpm check-dts
